import assert from 'node:assert/strict';
import * as T from '../dist/vendor/three.module.js';
import {BrushStroke,lineCells,brushCells,screenSamples,gestureIntent} from '../dist/brush.js';
import {TownMotion,motionPose} from '../dist/motion.js';
import {buildTown,BASE,FLOOR} from '../dist/model.js';
let town={};const stroke=new BrushStroke(town,{selected:1,style:2,rng:()=>.4});stroke.stamp(town,'0,0');stroke.stamp(town,'3,0');stroke.stamp(town,'0,0');assert.equal(Object.keys(town).length,4);assert(Object.values(town).every(b=>b.h===1&&b.c===1&&b.v===2));assert.equal(stroke.changed.size,4);assert.deepEqual(stroke.cancel(),{});const paint=new BrushStroke(town,{mode:'paint',selected:4,style:3,size:3});paint.stamp(town,'1,0');paint.stamp(town,'2,0');assert(Object.values(town).every(b=>b.c===4&&b.v===3));
const erase=new BrushStroke(town,{mode:'erase',eraseWhole:true,size:3});erase.stamp(town,'1,0');erase.stamp(town,'2,0');assert.deepEqual(town,{});assert.equal(erase.changed.size,4);town=erase.cancel();assert.equal(Object.keys(town).length,4);
const layer=new BrushStroke(town,{mode:'erase',eraseWhole:false});layer.stamp(town,'0,0');layer.stamp(town,'0,0');assert.equal(town['0,0'].h,0,'Revisiting during a stroke does not remove an extra layer');
assert.deepEqual(lineCells('0,0','3,0'),['0,0','1,0','2,0','3,0']);assert.equal(brushCells('0,0',5).length,25);assert.equal(brushCells('10,10',5).length,9);assert(screenSamples({clientX:0,clientY:0},{clientX:120,clientY:0}).length>=20);assert.equal(gestureIntent({button:0}),'pending');assert.equal(gestureIntent({continuous:true}),'brush');assert.equal(gestureIntent({shift:true}),'brush');assert.equal(gestureIntent({shift:true,pointerType:'touch'}),'pending');for(const settings of[{space:true},{touches:2},{button:2}])assert.equal(gestureIntent(settings),'camera');
const scene=new T.Scene(),data={'0,0':{x:0,z:0,h:2,c:1,v:0}},built=buildTown(data);scene.add(built.root);const motion=new TownMotion(scene);motion.bind(built);motion.intro(data,100);motion.update(100);const binding=built.motionBindings.find(b=>b.owners.length===1),m=new T.Matrix4();binding.mesh.getMatrixAt(binding.index,m);assert(m.elements[5]<binding.base.elements[5]*.1);motion.update(415);binding.mesh.getMatrixAt(binding.index,m);assert(m.elements[5]>binding.base.elements[5]*1.05,'Entrance overshoots before landing');motion.update(3000);binding.mesh.getMatrixAt(binding.index,m);assert(m.elements.every((v,i)=>Math.abs(v-binding.base.elements[i])<1e-5));assert.equal(motion.animations.size,0);
motion.trigger({key:'0,0',kind:'grow',before:{h:1},after:{h:2,c:1}},4000);motion.update(4100);const rebuilt=buildTown(data);motion.bind(rebuilt);motion.update(4200);assert(motion.animations.has('0,0'),'Animation survives a geometry rebuild');motion.update(5000);assert.equal(motion.animations.size,0);
motion.removeCell(built,'0,0',null,6000);assert.equal(motion.ghosts.length,1);motion.update(6200);assert(motion.ghosts[0].root.scale.y<1);motion.update(6400);assert.equal(motion.ghosts.length,0);motion.setReduced(true);motion.intro(data,7000);motion.trigger({key:'0,0',kind:'new',after:data['0,0']},7000);assert.equal(motion.animations.size,0);assert.equal(motion.ripples.length,0);
for(const kind of['new','intro','grow','paint','tap']){for(let i=0;i<=100;i++){const p=motionPose(kind,i/100);assert(Object.values(p).every(Number.isFinite));assert(p.sx>0&&p.sy>0)}assert.deepEqual(motionPose(kind,1),{sx:1,sy:1,lift:0})}
console.log('PASS: continuous brush coverage, per-stroke deduplication, batch paint/style/erase, cancel/undo snapshot, gesture routing, entrance overshoot, exact animation settling, animation rebind, removal cleanup, reduced motion.');
