import React from 'react';
import { Select as Primitive } from 'radix-ui';
import { Check, ChevronDown, ChevronUp } from 'lucide-react';
import { cn } from '@/lib/utils';
export const Select=Primitive.Root;
export const SelectValue=Primitive.Value;
export function SelectTrigger({className,children,...props}){return <Primitive.Trigger data-slot="select-trigger" className={cn('border-input data-[placeholder]:text-muted-foreground [&_svg]:text-muted-foreground focus-visible:border-ring focus-visible:ring-ring/50 flex w-fit items-center justify-between gap-2 rounded-md border bg-transparent px-3 py-2 text-sm shadow-xs transition-[color,box-shadow] outline-none focus-visible:ring-[3px] disabled:cursor-not-allowed disabled:opacity-50 [&_svg]:size-4 [&_svg]:shrink-0',className)} {...props}>{children}<Primitive.Icon asChild><ChevronDown className="size-4 opacity-50"/></Primitive.Icon></Primitive.Trigger>}
export function SelectContent({className,children,position='popper',...props}){return <Primitive.Portal><Primitive.Content data-slot="select-content" position={position} className={cn('bg-popover text-popover-foreground relative z-50 max-h-(--radix-select-content-available-height) min-w-[8rem] overflow-x-hidden overflow-y-auto rounded-md border shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=top]:slide-in-from-bottom-2',position==='popper'&&'data-[side=bottom]:translate-y-1 data-[side=top]:-translate-y-1',className)} {...props}><Primitive.ScrollUpButton className="flex justify-center py-1"><ChevronUp className="size-4"/></Primitive.ScrollUpButton><Primitive.Viewport className={cn('p-1',position==='popper'&&'w-full min-w-(--radix-select-trigger-width) scroll-my-1')}>{children}</Primitive.Viewport><Primitive.ScrollDownButton className="flex justify-center py-1"><ChevronDown className="size-4"/></Primitive.ScrollDownButton></Primitive.Content></Primitive.Portal>}
export function SelectItem({className,children,...props}){return <Primitive.Item data-slot="select-item" className={cn('focus:bg-accent focus:text-accent-foreground relative flex w-full cursor-default items-center gap-2 rounded-sm py-2 pr-8 pl-2 text-xs outline-hidden select-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50',className)} {...props}><span className="absolute right-2 flex size-3.5 items-center justify-center"><Primitive.ItemIndicator><Check className="size-4"/></Primitive.ItemIndicator></span><Primitive.ItemText>{children}</Primitive.ItemText></Primitive.Item>}
